### ISSUE TITLE
build key gone?

### ISSUE THREAD

**Issue by nthiery** [plgitlogin/premierlangage#118]
My [C++ exercises](https://github.com/PremierLangage/cpp-info111/)   (see e.g. [this one](https://github.com/PremierLangage/cpp-info111/blob/master/template/wims_code.pl)) are using a build function, specified in a build key:
```
build==
def build(exo):
    ...
    return ...
```
This worked last September, but not any more:
```
One of the following key must be present:  : 'builder or builder.py' in file home/cpp-info111/exercices/test/input.cpp.pl


DEBUG set to True - Showing Traceback :

Traceback (most recent call last):
  File "/srv/local/pl/premierlangage/server/serverpl/loader/loader.py", line 41, in load_file
    return load_pl(directory, rel_path)
  File "/srv/local/pl/premierlangage/server/serverpl/loader/loader.py", line 117, in load_pl
    dic, warnings = parse_file(directory, rel_path)
  File "/srv/local/pl/premierlangage/server/serverpl/loader/parser.py", line 166, in parse_file
    message="One of the following key must be present: ")
loader.exceptions.MissingKey: One of the following key must be present:  : 'builder or builder.py' in file home/cpp-info111/exercices/test/input.cpp.pl
```
Was something changed? E.g. deprecating functions in favour of build scripts? If not how should the build function be specified?

Thanks in advance,

**Comment by nthiery** [comment]
Thanks Quentin for the pointer! I was reading the documentation from
https://pl.u-pem.fr/documentation/ , which apparently is showing the old documentation.
